### ISSUE TITLE
Calling API with sampled data and use return values

### ISSUE THREAD

**Issue by mgerzabek** [quikstart/scripts#4]
Stumbled upon this helpful resource, thank you!

I want to …

(i) collect data with the provided commands
(ii) issue an HTTPS call to a backend API
(iii) gather the result and
(iv) create the scaffold.

Is this possible with this script? Any hints warmly welcomed. As you probably assumed, I’m a ruby novice… sorry for the dumb question in case…

**Comment by geraldb** [comment]
Yes, for sure.  Ruby is a general-purpose very high-level scripting language for automation and the wizard scripts are  ruby scripts (with some "built-in" pre-loaded helpers).   If you are new to ruby, please ask in r/ruby or such about recommendations on books, tutorials, etc to get started.
